[package]
name = "method"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2.0", default-features = false, features = ['std'] }
smartcore = { version = "0.3.2", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1.2"